# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Country')),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Metric')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='weatherreport',
            unique_together=set([('country', 'metric_type', 'year', 'month')]),
        ),
    ]
